# Author: Alon Wilson

from sqlmodel import create_engine, Session, SQLModel
from .config import settings

# Only apply sqlite connect_args when using sqlite
connect_args = {}
if settings.DATABASE_URL.startswith("sqlite"):
    connect_args = {"check_same_thread": False}

engine = create_engine(settings.DATABASE_URL, echo=settings.ECHO_SQL, connect_args=connect_args)

def init_db() -> None:
    from models.survey import Survey
    SQLModel.metadata.create_all(engine)

def get_session():
    with Session(engine) as session:
        yield session